dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { setUrl("https://jitpack.io") }
    }
}

pluginManagement {
    includeBuild("build-logic")
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
rootProject.name = "KAHelpers"
include(":dataStructuresAndAlgorithms")
include(":recyclerview")
include(":glide")
include(":moshi")
include(":gson")
include(":customviews")
include(":jodaDateTime")
include(":viewbinding")
include(":biometrics")
include(":reflection")
include(":rx")
include(":coroutines")
include(":retrofit")
include(":security")
include(":kotlinextensions")
include(":app")
include(":accessibility")
include(":animations")
include(":audio")
include(":activity")
include(":contextGetters")
include(":context")
include(":internetDetector")
include(":common")
include(":string")
include(":bytearray")
include(":file")
include(":resources")
include(":networking")
include(":http")
include(":view")
include(":viewpager2")
include(":dateTime")
include(":collections")
include(":root")
include(":fragment")
include(":enums")
include(":generators")
include(":math")
include(":locale")
include(":numbers")
include(":livedata")
include(":color")
include(":lifecycle")
include(":permissions")
include(":regex")
include(":photos")
include(":sharedpreferences")
include(":toaster")
include(":saf")
include(":intent")
include(":receivers")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
