-keep public class com.crazylegend.setofusefulkotlinextensions.TestAVM { public <init>(...); }
-keep public class com.crazylegend.setofusefulkotlinextensions.adapter.TestViewHolderBinding { public <init>(...); }
-keep public class com.crazylegend.setofusefulkotlinextensions.adapter.TestViewHolder { public <init>(...); }